version: '3.8'

services:
  wb-mqtt-bridge:
    build: 
      context: .
      args:
        # ARMv7 compatibility flags
        ARCH: arm32v7
    container_name: wb-mqtt-bridge
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      # Mount local dependency directories if they exist
      - ${PYMOTIVAXMC2_PATH:-../pymotivaxmc2}:/app/pymotivaxmc2:ro
      - ${ASYNCWEBOSTV_PATH:-../asyncwebostv}:/app/asyncwebostv:ro
      - ${ASYNCMIELE_PATH:-../asyncmiele}:/app/asyncmiele:ro
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-localhost}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app:/app/pymotivaxmc2:/app/asyncwebostv:/app/asyncmiele
    networks:
      - mqtt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # Limit resources on ARMv7 devices
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

networks:
  mqtt-network:
    driver: bridge 