version: '3.8'

services:
  wb-mqtt-bridge:
    build: 
      context: .
      args:
        # ARMv7 compatibility flags
        ARCH: arm32v7
    container_name: wb-mqtt-bridge
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      # Mount local dependency directories if they exist
      - ${PYMOTIVAXMC2_PATH:-../pymotivaxmc2}:/app/pymotivaxmc2:ro
      - ${ASYNCWEBOSTV_PATH:-../asyncwebostv}:/app/asyncwebostv:ro
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-localhost}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app:/app/pymotivaxmc2:/app/asyncwebostv
    networks:
      - mqtt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    # Specific ARM-compatible Nginx image based on Debian Bullseye for Wirenboard 7
    image: arm32v7/nginx:1.22-bullseye
    container_name: wb-mqtt-bridge-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8081}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - wb-mqtt-bridge
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge 